### login
POST http://localhost:35000/mobile/login
content-type: application/json

{
    "username":"admin",
    "password":"1234"
}

### JWT verify
GET http://localhost:35000/JWT

### test token
GET http://localhost:35000/mobile/verify
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjA5OTQ5MDgsImV4cCI6MTYyMTA4MTMwOH0.yKp93vKrvXyBRNoIDCldbritPRgxoaKQ1WiZiMnu44A

### get own product with category
GET http://localhost:35000/myproduct/1
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjA5OTQ5MDgsImV4cCI6MTYyMTA4MTMwOH0.yKp93vKrvXyBRNoIDCldbritPRgxoaKQ1WiZiMnu44A

### get product with category
GET http://localhost:35000/product/1
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjA5OTQ5MDgsImV4cCI6MTYyMTA4MTMwOH0.yKp93vKrvXyBRNoIDCldbritPRgxoaKQ1WiZiMnu44A

### get product with product id
POST http://localhost:35000/productDetail
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjA5OTQ5MDgsImV4cCI6MTYyMTA4MTMwOH0.yKp93vKrvXyBRNoIDCldbritPRgxoaKQ1WiZiMnu44A

{
    "ProductID":"2"
}


### sell product
PUT http://localhost:35000/sellproduct
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjA5OTQ5MDgsImV4cCI6MTYyMTA4MTMwOH0.yKp93vKrvXyBRNoIDCldbritPRgxoaKQ1WiZiMnu44A

{
    "ProductID":"2,3"
}

### out of order product amount is 0 
PUT http://localhost:35000/sellproduct
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjA5OTQ5MDgsImV4cCI6MTYyMTA4MTMwOH0.yKp93vKrvXyBRNoIDCldbritPRgxoaKQ1WiZiMnu44A

{
    "ProductID":"2,3"
}

### out of order product amount is 0 
GET http://localhost:35000/order/0
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjA5OTQ5MDgsImV4cCI6MTYyMTA4MTMwOH0.yKp93vKrvXyBRNoIDCldbritPRgxoaKQ1WiZiMnu44A


###
GET http://localhost:35000/profile/show
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjExMjA5MjAsImV4cCI6MTYyMTIwNzMyMH0.IajuiiiT42rwNuek7vuaJKVCfFJ9dl43Oom5tQmIv4k

###
put http://localhost:35000/profile/edit
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjExMjA5MjAsImV4cCI6MTYyMTIwNzMyMH0.IajuiiiT42rwNuek7vuaJKVCfFJ9dl43Oom5tQmIv4k

{
    "NameUser":"2,3",
    "UserEmail":"61313131",
    "UserTel":"08888888"
}

### register
POST http://localhost:35000/mobile/register
content-type: application/json

{
    "username" : "admin",
    "password" : "1234",
    "name" : "nutza",
    "email" : "nut_1234@hotmail.com",
    "phone" : "0834566544"
}